name = "notion-relay"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
SKIP_HOURS = "2,3,4,5"
